CompileFlags:
  Add:
    - -std=c++17 
    - -DLOCAL 
    - -g 
    - -O2
    - -Wconversion
    - -Wshadow 
    - -Wall 
    - -Wextra 
    - -D_GLIBCXX_DEBUG
    - -Wno-unused-const-variable


Index:
  Background: Skip
